<?php
	echo'<div class="menu">'.
			'<ul>'.
				'<li><a href="about.php">關於調酒</a>'.
					'<ul>'.
						'<li><a href="about.php#original" >起源</a></li>'.
						'<li><a href="about.php#feature">特點</a></li>'.
						'<li><a href="about.php#popularity">盛行</a></li>'.
						'<li><a href="about.php#question">常見問題</a></li>'.
					'</ul>'.
				'</li>'.
				'<li><a href="baseWine.php">六大基酒</a></li>'.
				'<li><a href="commonCocktail.php">常見調酒</a></li>'.
				'<li><a href="game.php">調酒大師</a></li>'.
				'<a href="index.php"><img src="images/title.png"></a>'.
			'</ul>'.
		'</div>';
?>